name: Build Win7 EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
  
    steps:
    - name: Code auschecken
      uses: actions/checkout@v4
  
    - name: Python 3.8 einrichten
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        
    - name: Pyinstaller installieren
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
  
    - name: Exe kompilieren
      run: |
        pyinstaller --onefile source/pdf_stamper.py
  
    - name: Fertige Exe hochladen
      uses: actions/upload-artifact@v4
      with:
        name: Windows7-Executable
        path: dist/*.exe
